import CampaignObjectives from '../models/ad/campaignObjectives';
import AdFormats from '../models/ad//adFormats';
import CallToActions from '../models/ad/callToActions';

// https://developers.facebook.com/docs/marketing-api/validation/v2.12
// https://www.facebook.com/business/ads-guide

// const Mapping = {
//   [AdFormat]: {
//     [CampaignObjective]: [CallToActions]
//   }
// }

const imageMapping = {
  [CampaignObjectives.reach]: [
    CallToActions.apply_now,
    CallToActions.book_travel,
    CallToActions.call_now,
    CallToActions.contact_us,
    CallToActions.download,
    CallToActions.get_directions,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.send_message,
    CallToActions.request_time,
    CallToActions.save,
    CallToActions.see_menu,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
    CallToActions.listen_now,
  ],

  [CampaignObjectives.brand_awareness]: [
    CallToActions.apply_now,
    CallToActions.book_travel,
    CallToActions.contact_us,
    CallToActions.download,
    CallToActions.learn_more,
    CallToActions.send_message,
    CallToActions.get_showtimes,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
    CallToActions.listen_now,
  ],
  [CampaignObjectives.link_clicks]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.contact_us,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.get_offer,
  ],
  [CampaignObjectives.link_clicks]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.contact_us,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.get_offer,
  ],
  [CampaignObjectives.post_engagement]: [
    CallToActions.learn_more,
    CallToActions.send_message,
    CallToActions.shop_now,
  ],
  [CampaignObjectives.page_likes]: [],
  [CampaignObjectives.event_responses]: [
    CallToActions.view_event,
  ],
  [CampaignObjectives.app_installs]: [
    CallToActions.install_now,
    CallToActions.use_app,
    CallToActions.book_travel,
    CallToActions.download,
    CallToActions.learn_more,
    CallToActions.listen_now,
    CallToActions.play_game,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
  ],
};

const videoMapping = {
  [CampaignObjectives.reach]: [
    CallToActions.apply_now,
    CallToActions.book_travel,
    CallToActions.call_now,
    CallToActions.contact_us,
    CallToActions.download,
    CallToActions.get_directions,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.send_message,
    CallToActions.request_time,
    CallToActions.save,
    CallToActions.see_menu,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
    CallToActions.listen_now,
  ],
  [CampaignObjectives.brand_awareness]: [
    CallToActions.apply_now,
    CallToActions.book_travel,
    CallToActions.call_now,
    CallToActions.contact_us,
    CallToActions.download,
    CallToActions.learn_more,
    CallToActions.send_message,
    CallToActions.get_showtimes,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
    CallToActions.listen_now,
  ],
  [CampaignObjectives.link_clicks]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.contact_us,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.get_offer,
  ],
  [CampaignObjectives.link_clicks]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.contact_us,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.get_offer,
  ],
  [CampaignObjectives.post_engagement]: [
    CallToActions.learn_more,
    CallToActions.send_message,
    CallToActions.shop_now,
  ],
  [CampaignObjectives.page_likes]: [],
  [CampaignObjectives.event_responses]: [
    CallToActions.view_event,
  ],
  [CampaignObjectives.app_installs]: [
    CallToActions.install_now,
    CallToActions.use_app,
    CallToActions.book_travel,
    CallToActions.download,
    CallToActions.learn_more,
    CallToActions.listen_now,
    CallToActions.play_game,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
  ],
  [CampaignObjectives.lead_generation]: [
    CallToActions.subscribe,
    CallToActions.sign_up,
    CallToActions.learn_more,
    CallToActions.apply_now,
    CallToActions.download,
    CallToActions.get_quote,
  ],
  [CampaignObjectives.video_views]: [
    CallToActions.shop_now,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.book_travel,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.send_message,
    CallToActions.listen_now,
  ],
  [CampaignObjectives.conversions]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.contact_us,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.play_game,
    CallToActions.get_offer,
  ],
  [CampaignObjectives.store_visits]: [
    CallToActions.call_now,
    CallToActions.get_directions,
    CallToActions.get_offer,
    CallToActions.learn_more,
    CallToActions.send_message,
    CallToActions.order_now,
    CallToActions.shop_now,
  ],
};

const carouselMapping = {
  [CampaignObjectives.reach]: [
    CallToActions.apply_now,
    CallToActions.book_travel,
    CallToActions.call_now,
    CallToActions.contact_us,
    CallToActions.download,
    CallToActions.get_directions,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.send_message,
    CallToActions.request_time,
    CallToActions.save,
    CallToActions.see_menu,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
    CallToActions.listen_now,
  ],
  [CampaignObjectives.brand_awareness]: [
    CallToActions.apply_now,
    CallToActions.book_travel,
    CallToActions.contact_us,
    CallToActions.download,
    CallToActions.learn_more,
    CallToActions.send_message,
    CallToActions.get_showtimes,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
    CallToActions.listen_now,
  ],
  [CampaignObjectives.link_clicks]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.contact_us,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.get_offer,
  ],
  [CampaignObjectives.link_clicks]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.contact_us,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.get_offer,
  ],
  [CampaignObjectives.app_installs]: [
    CallToActions.install_now,
    CallToActions.use_app,
    CallToActions.book_travel,
    CallToActions.download,
    CallToActions.learn_more,
    CallToActions.listen_now,
    CallToActions.play_game,
    CallToActions.shop_now,
    CallToActions.sign_up,
    CallToActions.watch_more,
  ],
  [CampaignObjectives.lead_generation]: [
    CallToActions.subscribe,
    CallToActions.sign_up,
    CallToActions.learn_more,
    CallToActions.apply_now,
    CallToActions.download,
    CallToActions.get_quote,
  ],
  [CampaignObjectives.conversions]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.watch_more,
    CallToActions.apply_now,
    CallToActions.donate_now,
    CallToActions.contact_us,
    CallToActions.request_time,
    CallToActions.see_menu,
    CallToActions.send_message,
    CallToActions.listen_now,
    CallToActions.play_game,
  ],
  [CampaignObjectives.product_catalog_sales]: [
    CallToActions.shop_now,
    CallToActions.book_travel,
    CallToActions.learn_more,
    CallToActions.get_showtimes,
    CallToActions.sign_up,
    CallToActions.download,
    CallToActions.open_link,
    CallToActions.donate_now,
    CallToActions.listen_now,
  ],
};

const collectionMapping = {
  [CampaignObjectives.link_clicks]: [],
  [CampaignObjectives.conversions]: [],
  [CampaignObjectives.store_visits]: [],
};


const CallToActionMapping = {
  //video
  [AdFormats.video]: videoMapping,
  [AdFormats.slideshow]: videoMapping,

  //image
  [AdFormats.image]: imageMapping,

  //carousel
  [AdFormats.carousel]: carouselMapping,

  //collection
  [AdFormats.collection]: collectionMapping,
}


export default CallToActionMapping;
